[package]
name = "wisp-keyring"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
keyring = { version = "3.6.2", features = [
    "apple-native",
    "windows-native",
    "linux-native-async-persistent",
    "crypto-rust",
    "tokio",
] }
rusqlite = { version = "0.35.0", features = ["bundled"] }
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.22"
