[package]
name = "wisp-llm"
version.workspace = true
edition.workspace = true

[dependencies]
wisp-configs.workspace = true
wisp-keyring.workspace = true
rig-core.workspace = true
tokio.workspace = true
tokio-util.workspace = true
thiserror.workspace = true
futures.workspace = true
serde_json.workspace = true

[dev-dependencies]
http = "1"
